### ISSUE TITLE
TODO, Brainstorm.

### ISSUE THREAD

**Issue by alex2wong** [alex2wong/mapbox-plugins#2]
- [ ]  write blog sharing async/await in scene animation control.

- [ ]  build voxelized terrain using extrusion layer in Mapbox (inspired by Minecraft World)

- [ ]  refactor route animation, simplify api.

**Comment by alex2wong** [comment]
- [ ] submit directional line style, inspired by AMap from Gaode

**Comment by alex2wong** [comment]
- [ ] try hacking webgl renderer of mapbox, add some stuff..
